{{- if .Values.httpRoute.enabled }}
---
# Production HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "canary.fullname" . }}-production
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canary.labels" . | nindent 4 }}
    route-type: production
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: my-gateway
    namespace: {{ .Release.Namespace }}
  {{- with .Values.httpRoute.production.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.production.rules }}
  - matches:
    {{- toYaml .matches | nindent 4 }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .weight }}
      weight: {{ .weight }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
