apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "canary.fullname" . }}
  labels:
    {{- include "canary.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "canary.labels" . | nindent 6 }}
  strategy:
    canary:
      stableService: {{ template "canary.fullname" . }}-stable
      canaryService: {{ template "canary.fullname" . }}-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: canary-production
            namespace: default
      steps:
      - setWeight: 25
      - pause: {}              # Manual promotion
      - setWeight: 50
      - pause: {duration: 10m}
      - setWeight: 75
      - pause: {duration: 5m}
  template:
    metadata:
      labels:
        {{- include "canary.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
