apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argoroll.fullname" . }}
  labels:
    app: {{ include "argoroll.name" . }}
    chart: {{ include "argoroll.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "argoroll.name" . }}
      release: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: {{ include "argoroll.fullname" . }}
      previewService: {{ include "argoroll.fullname" . }}-preview
      autoPromotionEnabled: false    # ← Manual promotion (safer)
      scaleDownDelaySeconds: 30      # ← Time before scaling down old version
      previewReplicaCount: 1
  template:
    metadata:
      labels:
        app: {{ include "argoroll.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
